# Nixpacks configuration for Railway deployment
# Optimized for reliability over speed

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install"
]

[start]
cmd = "node src/autonomous-engine.js"