# Nixpacks configuration for faster Railway builds

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --omit=dev --ignore-scripts"
]

[phases.build]
cmds = []

[start]
cmd = "node src/autonomous-engine.js"