# Nixpacks configuration for faster Railway builds

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --production --prefer-offline --no-audit"
]

[start]
cmd = "node src/autonomous-engine.js"